{application,todo,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"todo"},
              {modules,['Elixir.Todo.Cache','Elixir.Todo.Database',
                        'Elixir.Todo.DatabaseWorker','Elixir.Todo.List',
                        'Elixir.Todo.Server']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
